# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.29

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/homebrew/Cellar/cmake/3.29.0/bin/cmake

# The command to remove a file.
RM = /opt/homebrew/Cellar/cmake/3.29.0/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/chenchengxi/Desktop/MyProject/efiXplorer

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/chenchengxi/Desktop/MyProject/efiXplorer

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/opt/homebrew/Cellar/cmake/3.29.0/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/opt/homebrew/Cellar/cmake/3.29.0/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/chenchengxi/Desktop/MyProject/efiXplorer/CMakeFiles /Users/chenchengxi/Desktop/MyProject/efiXplorer//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/chenchengxi/Desktop/MyProject/efiXplorer/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named efiXplorer.dylib

# Build rule for target.
efiXplorer.dylib: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 efiXplorer.dylib
.PHONY : efiXplorer.dylib

# fast build rule for target.
efiXplorer.dylib/fast:
	$(MAKE) $(MAKESILENT) -f efiXplorer/CMakeFiles/efiXplorer.dylib.dir/build.make efiXplorer/CMakeFiles/efiXplorer.dylib.dir/build
.PHONY : efiXplorer.dylib/fast

#=============================================================================
# Target rules for targets named efiXplorer64.dylib

# Build rule for target.
efiXplorer64.dylib: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 efiXplorer64.dylib
.PHONY : efiXplorer64.dylib

# fast build rule for target.
efiXplorer64.dylib/fast:
	$(MAKE) $(MAKESILENT) -f efiXplorer/CMakeFiles/efiXplorer64.dylib.dir/build.make efiXplorer/CMakeFiles/efiXplorer64.dylib.dir/build
.PHONY : efiXplorer64.dylib/fast

#=============================================================================
# Target rules for targets named efiXplorer_lib_ea32

# Build rule for target.
efiXplorer_lib_ea32: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 efiXplorer_lib_ea32
.PHONY : efiXplorer_lib_ea32

# fast build rule for target.
efiXplorer_lib_ea32/fast:
	$(MAKE) $(MAKESILENT) -f efiXplorer/CMakeFiles/efiXplorer_lib_ea32.dir/build.make efiXplorer/CMakeFiles/efiXplorer_lib_ea32.dir/build
.PHONY : efiXplorer_lib_ea32/fast

#=============================================================================
# Target rules for targets named efiXplorer_lib_ea64

# Build rule for target.
efiXplorer_lib_ea64: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 efiXplorer_lib_ea64
.PHONY : efiXplorer_lib_ea64

# fast build rule for target.
efiXplorer_lib_ea64/fast:
	$(MAKE) $(MAKESILENT) -f efiXplorer/CMakeFiles/efiXplorer_lib_ea64.dir/build.make efiXplorer/CMakeFiles/efiXplorer_lib_ea64.dir/build
.PHONY : efiXplorer_lib_ea64/fast

#=============================================================================
# Target rules for targets named efiXloader64.dylib

# Build rule for target.
efiXloader64.dylib: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 efiXloader64.dylib
.PHONY : efiXloader64.dylib

# fast build rule for target.
efiXloader64.dylib/fast:
	$(MAKE) $(MAKESILENT) -f efiXloader/CMakeFiles/efiXloader64.dylib.dir/build.make efiXloader/CMakeFiles/efiXloader64.dylib.dir/build
.PHONY : efiXloader64.dylib/fast

#=============================================================================
# Target rules for targets named efiXloader_lib_ea32

# Build rule for target.
efiXloader_lib_ea32: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 efiXloader_lib_ea32
.PHONY : efiXloader_lib_ea32

# fast build rule for target.
efiXloader_lib_ea32/fast:
	$(MAKE) $(MAKESILENT) -f efiXloader/CMakeFiles/efiXloader_lib_ea32.dir/build.make efiXloader/CMakeFiles/efiXloader_lib_ea32.dir/build
.PHONY : efiXloader_lib_ea32/fast

#=============================================================================
# Target rules for targets named efiXloader_lib_ea64

# Build rule for target.
efiXloader_lib_ea64: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 efiXloader_lib_ea64
.PHONY : efiXloader_lib_ea64

# fast build rule for target.
efiXloader_lib_ea64/fast:
	$(MAKE) $(MAKESILENT) -f efiXloader/CMakeFiles/efiXloader_lib_ea64.dir/build.make efiXloader/CMakeFiles/efiXloader_lib_ea64.dir/build
.PHONY : efiXloader_lib_ea64/fast

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... efiXloader64.dylib"
	@echo "... efiXloader_lib_ea32"
	@echo "... efiXloader_lib_ea64"
	@echo "... efiXplorer.dylib"
	@echo "... efiXplorer64.dylib"
	@echo "... efiXplorer_lib_ea32"
	@echo "... efiXplorer_lib_ea64"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

